// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Explicit, operator-invoked only: `npm run db:seed` (`prisma db seed`).
    // Seed execution is never attached to `migrate`, `build` or `postinstall`.
    //
    // `jiti` runs prisma/seed.ts because Prisma 7 emits its client as TypeScript
    // with extensionless relative imports, which Node's native type stripping
    // cannot resolve. `jiti` already ships with this repo's toolchain.
    seed: "jiti prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
